server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_oms
    username: zhangsan
    password: 123456
  redis:
    host: 192.168.56.129
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true #是否监听zipkin的请求
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
mybatis-plus:
  mapper-locations: classpath:mapper/oms/**/*.xml
  type-aliases-package: com.atguigu.gmall.oms.entity #别名扫描
  global-config:
    db-config:
      id-type: auto
feign:
  sentinel:
    enabled: true



